# Generated by Django 4.2.2 on 2023-11-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bet_match_pointstransaction_user_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstransaction',
            name='transaction_type',
        ),
    ]
