# Generated by Django 4.2.7 on 2023-12-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_userprofile_alter_bet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_data',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bet_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WinnerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_team', models.CharField(max_length=100)),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bet', to='main.bet')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_bet', to='main.bet')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_to_score', models.CharField(max_length=255)),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_bet', to='main.bet')),
            ],
        ),
    ]
