# Generated by Django 4.2.7 on 2023-12-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bet_bet_data_remove_bet_bet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
    ]
