# Generated by Django 4.2.7 on 2023-12-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_bet_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.match'),
        ),
    ]
