# Generated by Django 4.2.7 on 2023-12-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bet_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
