# Generated by Django 4.2.7 on 2024-01-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userprofile_points_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points_balance',
            field=models.IntegerField(default=500),
        ),
    ]
