# Generated by Django 4.2.7 on 2024-01-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_points_balance'),
    ]

    operations = [
    ]
