# Generated by Django 4.2.7 on 2024-01-04 10:12

from django.db import migrations


def set_default_points(apps, schema_editor):
    UserProfile = apps.get_model('main', 'UserProfile')
    UserProfile.objects.all().update(points_balance=500)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240104_1006'),
    ]

    operations = [
        migrations.RunPython(set_default_points),
    ]
