# Generated by Django 4.2.7 on 2024-01-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20240104_1012'),
        ('main', '0014_auto_20240104_1040'),
    ]

    operations = [
    ]
