# Generated by Django 4.2.7 on 2024-01-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_0013_auto_20240104_1012_0014_auto_20240104_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
