# Generated by Django 4.2.7 on 2024-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('winner', 'Winner Bet'), ('score', 'Score Bet'), ('player', 'Player Bet')], max_length=20, null=True),
        ),
    ]
