# Generated by Django 4.2.7 on 2024-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_bet_bet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fixture_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
