# Generated by Django 4.2.7 on 2024-01-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_match_fixture_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_time',
        ),
    ]
