# Generated by Django 4.2.7 on 2024-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_match_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
