# Generated by Django 4.2.7 on 2024-01-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bet_bet_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('Winner', 'Winner Bet'), ('Score', 'Score Bet'), ('Player', 'Player Bet')], max_length=20, null=True),
        ),
    ]
