# Generated by Django 4.2.7 on 2024-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_bet_bet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10),
        ),
    ]
