# Generated by Django 4.2.7 on 2024-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bet_bet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
