# Generated by Django 4.2.7 on 2024-01-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_match_match_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_status',
        ),
    ]
