# Generated by Django 4.2.7 on 2024-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_match_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
