# Generated by Django 4.2.7 on 2024-01-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_scorebet_score_prediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsTransaction',
        ),
    ]
