# Generated by Django 4.2.7 on 2024-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_pointstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_points_won',
            field=models.IntegerField(default=0),
        ),
    ]
