# Generated by Django 4.2.7 on 2024-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_userprofile_total_points_placed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='percentage_of_points_won',
            field=models.FloatField(default=0.0),
        ),
    ]
