# Generated by Django 4.2.7 on 2024-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userprofile_percentage_of_points_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_added_this_week',
            field=models.BooleanField(default=False),
        ),
    ]
