# Generated by Django 4.2.7 on 2024-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_userprofile_points_added_this_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
