# Generated by Django 4.2.7 on 2024-01-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_userprofile_last_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points_added_this_week',
        ),
    ]
