# Generated by Django 4.2.7 on 2024-01-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_userprofile_points_added_this_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerBet',
        ),
    ]
