# Generated by Django 4.2.7 on 2024-03-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_delete_playerbet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_team',
            new_name='favourite_team',
        ),
    ]
