# Generated by Django 4.2.7 on 2024-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_favorite_team_userprofile_favourite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('Winner', 'Winner Bet'), ('Score', 'Score Bet')], max_length=20, null=True),
        ),
    ]
