# Generated by Django 4.2.7 on 2024-04-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_thread_threadparticipant_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadParticipant',
        ),
    ]
