# Generated by Django 4.2.7 on 2024-04-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_delete_threadparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
    ]
